# Site settings
title: David Chapman

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

url: "http://d3chapma.github.io" # the base hostname & protocol for your site
twitter_username: d3chapma
github_username:  d3chapma

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
